site_name: SteamVR Documentation
theme: readthedocs

nav:
  - Home: 'index.md'
  - 'HDK Tutorials':
    - 'Pairing your HDK': 'pairing_instructions.md'
    - 'Optical Calibration': 'optical_calibration.md'
    - 'IMU Calibration': 'imu_calibration.md'