site_name: SteamVR Documentation
theme: readthedocs

nav:
  - 'HDK Tutorials':
    - 'Pairing your HDK': 'pairing_instructions.md'
    - 'Optical Calibration': 'optical_calibration.md'
    - 'Bootloader': 'bootloader.md'
    - Home: 'index.md'